"""create tables

Revision ID: eb26d667db9e
Revises: 
Create Date: 2025-11-29 22:55:42.291822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb26d667db9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('otp', sa.String(length=6), nullable=True),
    sa.Column('otp_expires', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=250), nullable=True),
    sa.Column('cac', sa.String(length=250), nullable=True),
    sa.Column('business_name', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admin_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('amount', sa.Float(precision=400), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bank_code', sa.String(length=20), nullable=False),
    sa.Column('recipient_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_number', 'bank_code', name='unique_user_bank_account')
    )
    op.create_table('merchant_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('escrow_code', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('merchant_name', sa.String(length=250), nullable=False),
    sa.Column('merchant_email', sa.String(length=250), nullable=False),
    sa.Column('reference', sa.String(length=150), nullable=False),
    sa.Column('external_reference', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.Float(precision=400), nullable=False),
    sa.Column('merchant_percentage', sa.Float(precision=8), nullable=True),
    sa.Column('expected_profit', sa.Float(precision=400), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('customer_email', sa.String(length=150), nullable=False),
    sa.Column('webhook_url', sa.String(length=250), nullable=False),
    sa.Column('platform', sa.String(length=250), nullable=False),
    sa.Column('dispute_reason', sa.String(length=500), nullable=True),
    sa.Column('settlement_account', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profit_balance', sa.Float(precision=400), nullable=True),
    sa.Column('total_escrowed_funds', sa.Float(precision=1000), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('is_frozen', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    op.drop_table('merchant_transactions')
    op.drop_table('banks')
    op.drop_table('admin_transactions')
    op.drop_table('users')
    # ### end Alembic commands ###
